import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'staging', 'production').default('development'),
  PORT: Joi.number().default(3000),
  API_PREFIX: Joi.string().default('api/v1'),

  DATABASE_HOST: Joi.string().required(),
  DATABASE_PORT: Joi.number().default(5432),
  DATABASE_USER: Joi.string().required(),
  DATABASE_PASSWORD: Joi.string().required(),
  DATABASE_NAME: Joi.string().required(),
  DATABASE_SSL: Joi.boolean().truthy('true').falsy('false').default(false),

  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),

  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: Joi.string().default('7d'),

  CORS_ORIGINS: Joi.string().default('http://localhost:3001'),

  /** Paste from Google Cloud Console — server key (IP restricted). Empty = Haversine fallback. */
  GOOGLE_MAPS_API_KEY: Joi.string().allow('').optional(),
  TRACKING_MODE: Joi.string()
    .valid('phone_primary', 'hardware_primary', 'hybrid')
    .default('phone_primary'),
  TRACKING_ROUTE_DEVIATION_METERS: Joi.number().default(120),
  TRACKING_ETA_GRACE_SECONDS: Joi.number().default(180),
  LOCATION_ACCURACY_THRESHOLD_M: Joi.number().default(80),
  MOVING_SPEED_THRESHOLD_MPS: Joi.number().default(1.5),
  STOPPED_SPEED_THRESHOLD_MPS: Joi.number().default(0.6),
  MIN_DISTANCE_INTERVAL_M: Joi.number().default(12),
  MAX_TELEPORT_SPEED_MPS: Joi.number().default(55),
  STOP_RADIUS_M: Joi.number().default(40),
  STOP_MIN_DURATION_SEC: Joi.number().default(180),
  MOVING_CONFIRM_SEC: Joi.number().default(8),
  STOPPED_CONFIRM_SEC: Joi.number().default(45),
  PRESENCE_LIVE_SEC: Joi.number().default(30),
  PRESENCE_DELAYED_SEC: Joi.number().default(90),
  PRESENCE_STALE_SEC: Joi.number().default(300),
  PRESENCE_OFFLINE_SEC: Joi.number().default(300),
  LOCATION_UPLOAD_BATCH_SIZE: Joi.number().default(50),
  REDIS_TRACKING_TTL_SEC: Joi.number().default(600),
  TRACKING_ROADS_SNAP_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  TRACKING_HISTORY_RETENTION_DAYS: Joi.number().default(365),
  WHATSAPP_ACCESS_TOKEN: Joi.string().allow('').optional(),
  WHATSAPP_VERIFY_TOKEN: Joi.string().allow('').optional(),
  WHATSAPP_PHONE_NUMBER_ID: Joi.string().allow('').optional(),
  WHATSAPP_BUSINESS_ACCOUNT_ID: Joi.string().allow('').optional(),
  WHATSAPP_APP_SECRET: Joi.string().allow('').optional(),
  WHATSAPP_API_VERSION: Joi.string().default('v21.0'),
  OPENAI_API_KEY: Joi.string().allow('').optional(),
  OPENAI_TRANSPORT_MODEL: Joi.string().default('gpt-4o'),
  GEMINI_API_KEY: Joi.string().allow('').optional(),
  AI_PROVIDER: Joi.string().valid('openai', 'gemini', 'mock').default('mock'),
  AI_CONFIDENCE_THRESHOLD: Joi.number().min(0).max(1).default(0.75),

  DISPATCH_OFFER_TIMEOUT_SECONDS: Joi.number().default(45),
  GPS_OFFLINE_THRESHOLD_SECONDS: Joi.number().default(120),
  LOCATION_LIVE_SECONDS: Joi.number().default(30),
  LOCATION_DELAYED_SECONDS: Joi.number().default(120),
  UNAUTHORIZED_MOVEMENT_DISTANCE_METERS: Joi.number().default(300),
  UNAUTHORIZED_MOVEMENT_DURATION_SECONDS: Joi.number().default(120),
  UNAUTHORIZED_MOVEMENT_MIN_ACCURACY_METERS: Joi.number().default(50),
  RIDER_SEARCH_RADIUS_METERS: Joi.number().default(10000),
  RIDER_LOCATION_MAX_AGE_SECONDS: Joi.number().default(60),
  ASSIGNMENT_CANDIDATE_LIMIT: Joi.number().default(10),
  ASSIGNMENT_MATRIX_FALLBACK: Joi.boolean().truthy('true').falsy('false').default(true),

  SWAGGER_ENABLED: Joi.boolean().truthy('true').falsy('false').default(true),
  THROTTLE_TTL_MS: Joi.number().default(60000),
  THROTTLE_LIMIT: Joi.number().default(120),
  WORKER_MODE: Joi.boolean().truthy('true').falsy('false').default(false),
  DATABASE_SYNC: Joi.boolean().truthy('true').falsy('false').default(false),
  GPS_API_KEY: Joi.string().allow('').optional(),
});
