export enum CompanyStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
  REJECTED = 'REJECTED',
}

export enum CompanyDocumentType {
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  TAX_CLEARANCE = 'TAX_CLEARANCE',
  DIRECTOR_ID = 'DIRECTOR_ID',
  OTHER = 'OTHER',
}

export enum CompanyDocumentStatus {
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  ACCOUNTANT = 'ACCOUNTANT',
  RIDER = 'RIDER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
  LEFT = 'LEFT',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum RiderStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum RiderAvailabilityStatus {
  OFFLINE = 'OFFLINE',
  AVAILABLE = 'AVAILABLE',
  AWAITING_AVAILABILITY = 'AWAITING_AVAILABILITY',
  BUSY = 'BUSY',
  RESERVED = 'RESERVED',
  ASSIGNED = 'ASSIGNED',
  TO_PICKUP = 'TO_PICKUP',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  ON_TRIP = 'ON_TRIP',
}

export enum MotorcycleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  SUSPENDED = 'SUSPENDED',
}

export enum MotorcycleTrackingStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  PARKED = 'PARKED',
  MOVING = 'MOVING',
  UNAUTHORIZED_MOVEMENT = 'UNAUTHORIZED_MOVEMENT',
}

export enum GPSDeviceStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OFFLINE = 'OFFLINE',
  FAULTY = 'FAULTY',
}

export enum LocationSource {
  RIDER_APP = 'RIDER_APP',
  GPS_DEVICE = 'GPS_DEVICE',
}

export enum TrackingSessionStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  INTERRUPTED = 'INTERRUPTED',
}

export enum TrackingMovementState {
  OFF_DUTY = 'OFF_DUTY',
  READY = 'READY',
  TRACKING = 'TRACKING',
  MOVING = 'MOVING',
  STOPPED = 'STOPPED',
  OFFLINE = 'OFFLINE',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
}

export enum TrackingPresenceState {
  LIVE = 'LIVE',
  DELAYED = 'DELAYED',
  STALE = 'STALE',
  OFFLINE = 'OFFLINE',
}

export enum GeofenceType {
  HEAD_OFFICE = 'HEAD_OFFICE',
  WAREHOUSE = 'WAREHOUSE',
  CUSTOMER = 'CUSTOMER',
  PARKING = 'PARKING',
  DEPOT = 'DEPOT',
  CHECKPOINT = 'CHECKPOINT',
  DELIVERY_ZONE = 'DELIVERY_ZONE',
  OTHER = 'OTHER',
}

export enum GeofenceEventType {
  ENTER = 'ENTER',
  EXIT = 'EXIT',
}

export enum TransportRequestChannel {
  WHATSAPP = 'WHATSAPP',
  WEB = 'WEB',
  ADMIN = 'ADMIN',
}

export enum TransportRequestStatus {
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  DISPATCHING = 'DISPATCHING',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
}

export enum ApprovalAction {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TripStatus {
  SEARCHING_RIDER = 'SEARCHING_RIDER',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  RIDER_TO_PICKUP = 'RIDER_TO_PICKUP',
  RIDER_ARRIVED = 'RIDER_ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_RIDER_AVAILABLE = 'NO_RIDER_AVAILABLE',
}

export enum TripEventType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  DISPATCH_STARTED = 'DISPATCH_STARTED',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  RIDER_DECLINED = 'RIDER_DECLINED',
  RIDER_ARRIVED = 'RIDER_ARRIVED',
  TRIP_STARTED = 'TRIP_STARTED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  TRIP_CANCELLED = 'TRIP_CANCELLED',
  RIDER_REASSIGNED = 'RIDER_REASSIGNED',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
}

export enum BillingStatus {
  PENDING = 'PENDING',
  BILLED = 'BILLED',
  INVOICED = 'INVOICED',
  CANCELLED = 'CANCELLED',
}

export enum BillingPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

export enum BillingDistanceSource {
  ROUTE_ESTIMATE = 'ROUTE_ESTIMATE',
  GPS_DISTANCE = 'GPS_DISTANCE',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum IncidentType {
  UNAUTHORIZED_MOVEMENT = 'UNAUTHORIZED_MOVEMENT',
  GPS_OFFLINE = 'GPS_OFFLINE',
  GPS_DELAYED = 'GPS_DELAYED',
  RIDER_OFFLINE_DURING_TRIP = 'RIDER_OFFLINE_DURING_TRIP',
  ROUTE_DEVIATION = 'ROUTE_DEVIATION',
  LONG_STOP = 'LONG_STOP',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
}

export enum NotificationType {
  TRANSPORT_REQUEST = 'TRANSPORT_REQUEST',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  TRIP_ASSIGNMENT = 'TRIP_ASSIGNMENT',
  TRIP_UPDATED = 'TRIP_UPDATED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  GPS_ALERT = 'GPS_ALERT',
  INCIDENT = 'INCIDENT',
  BILLING = 'BILLING',
  INVOICE = 'INVOICE',
  SYSTEM = 'SYSTEM',
}

export enum WhatsAppConversationState {
  NEW = 'NEW',
  PARSING = 'PARSING',
  WAITING_FOR_PICKUP = 'WAITING_FOR_PICKUP',
  WAITING_FOR_DESTINATION = 'WAITING_FOR_DESTINATION',
  WAITING_FOR_TIME = 'WAITING_FOR_TIME',
  WAITING_FOR_LOCATION_SELECTION = 'WAITING_FOR_LOCATION_SELECTION',
  READY_FOR_CONFIRMATION = 'READY_FOR_CONFIRMATION',
  SUBMITTED = 'SUBMITTED',
  AWAITING_SUPERVISOR = 'AWAITING_SUPERVISOR',
  APPROVED = 'APPROVED',
  ASSIGNING_RIDER = 'ASSIGNING_RIDER',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum WhatsAppMessageDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

export enum WhatsAppProcessingStatus {
  RECEIVED = 'RECEIVED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
  DUPLICATE = 'DUPLICATE',
}

export enum TransportParseIntent {
  CREATE_TRANSPORT_REQUEST = 'CREATE_TRANSPORT_REQUEST',
  CHECK_REQUEST_STATUS = 'CHECK_REQUEST_STATUS',
  CANCEL_REQUEST = 'CANCEL_REQUEST',
  CHANGE_REQUEST = 'CHANGE_REQUEST',
  GREETING = 'GREETING',
  HELP = 'HELP',
  UNKNOWN = 'UNKNOWN',
}

export enum AssignmentMethod {
  ROUTE_MATRIX = 'ROUTE_MATRIX',
  POSTGIS_FALLBACK = 'POSTGIS_FALLBACK',
  MANUAL = 'MANUAL',
}

export enum ErrorCode {
  COMPANY_ACCESS_DENIED = 'COMPANY_ACCESS_DENIED',
  REQUEST_ALREADY_PROCESSED = 'REQUEST_ALREADY_PROCESSED',
  RIDER_NOT_AVAILABLE = 'RIDER_NOT_AVAILABLE',
  MOTORCYCLE_NOT_AVAILABLE = 'MOTORCYCLE_NOT_AVAILABLE',
  NO_RIDER_AVAILABLE = 'NO_RIDER_AVAILABLE',
  TRIP_INVALID_STATE = 'TRIP_INVALID_STATE',
  TRIP_ALREADY_COMPLETED = 'TRIP_ALREADY_COMPLETED',
  GPS_DEVICE_NOT_ASSIGNED = 'GPS_DEVICE_NOT_ASSIGNED',
  INCIDENT_ALREADY_RESOLVED = 'INCIDENT_ALREADY_RESOLVED',
  BILLING_RECORD_EXISTS = 'BILLING_RECORD_EXISTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
