export enum CompanyStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  RIDER = 'RIDER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum MembershipStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
  LEFT = 'LEFT',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum RiderStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum RiderAvailabilityStatus {
  OFFLINE = 'OFFLINE',
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  ASSIGNED = 'ASSIGNED',
  TO_PICKUP = 'TO_PICKUP',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  ON_TRIP = 'ON_TRIP',
}

export enum MotorcycleStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  MAINTENANCE = 'MAINTENANCE',
  SUSPENDED = 'SUSPENDED',
}

export enum MotorcycleTrackingStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  PARKED = 'PARKED',
  MOVING = 'MOVING',
  UNAUTHORIZED_MOVEMENT = 'UNAUTHORIZED_MOVEMENT',
}

export enum GPSDeviceStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OFFLINE = 'OFFLINE',
  FAULTY = 'FAULTY',
}

export enum LocationSource {
  RIDER_APP = 'RIDER_APP',
  GPS_DEVICE = 'GPS_DEVICE',
}

export enum TransportRequestChannel {
  WHATSAPP = 'WHATSAPP',
  WEB = 'WEB',
  ADMIN = 'ADMIN',
}

export enum TransportRequestStatus {
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  DISPATCHING = 'DISPATCHING',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
}

export enum ApprovalAction {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TripStatus {
  SEARCHING_RIDER = 'SEARCHING_RIDER',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  RIDER_TO_PICKUP = 'RIDER_TO_PICKUP',
  RIDER_ARRIVED = 'RIDER_ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_RIDER_AVAILABLE = 'NO_RIDER_AVAILABLE',
}

export enum TripEventType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  DISPATCH_STARTED = 'DISPATCH_STARTED',
  RIDER_ASSIGNED = 'RIDER_ASSIGNED',
  RIDER_ACCEPTED = 'RIDER_ACCEPTED',
  RIDER_DECLINED = 'RIDER_DECLINED',
  RIDER_ARRIVED = 'RIDER_ARRIVED',
  TRIP_STARTED = 'TRIP_STARTED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  TRIP_CANCELLED = 'TRIP_CANCELLED',
  RIDER_REASSIGNED = 'RIDER_REASSIGNED',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
}

export enum BillingStatus {
  PENDING = 'PENDING',
  BILLED = 'BILLED',
  INVOICED = 'INVOICED',
  CANCELLED = 'CANCELLED',
}

export enum BillingPeriod {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}

export enum BillingDistanceSource {
  ROUTE_ESTIMATE = 'ROUTE_ESTIMATE',
  GPS_DISTANCE = 'GPS_DISTANCE',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum IncidentType {
  UNAUTHORIZED_MOVEMENT = 'UNAUTHORIZED_MOVEMENT',
  GPS_OFFLINE = 'GPS_OFFLINE',
  GPS_DELAYED = 'GPS_DELAYED',
  RIDER_OFFLINE_DURING_TRIP = 'RIDER_OFFLINE_DURING_TRIP',
  ROUTE_DEVIATION = 'ROUTE_DEVIATION',
  LONG_STOP = 'LONG_STOP',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum IncidentStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
}

export enum NotificationType {
  TRANSPORT_REQUEST = 'TRANSPORT_REQUEST',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  TRIP_ASSIGNMENT = 'TRIP_ASSIGNMENT',
  TRIP_UPDATED = 'TRIP_UPDATED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  GPS_ALERT = 'GPS_ALERT',
  INCIDENT = 'INCIDENT',
  BILLING = 'BILLING',
  INVOICE = 'INVOICE',
  SYSTEM = 'SYSTEM',
}

export enum ErrorCode {
  COMPANY_ACCESS_DENIED = 'COMPANY_ACCESS_DENIED',
  REQUEST_ALREADY_PROCESSED = 'REQUEST_ALREADY_PROCESSED',
  RIDER_NOT_AVAILABLE = 'RIDER_NOT_AVAILABLE',
  MOTORCYCLE_NOT_AVAILABLE = 'MOTORCYCLE_NOT_AVAILABLE',
  NO_RIDER_AVAILABLE = 'NO_RIDER_AVAILABLE',
  TRIP_INVALID_STATE = 'TRIP_INVALID_STATE',
  TRIP_ALREADY_COMPLETED = 'TRIP_ALREADY_COMPLETED',
  GPS_DEVICE_NOT_ASSIGNED = 'GPS_DEVICE_NOT_ASSIGNED',
  INCIDENT_ALREADY_RESOLVED = 'INCIDENT_ALREADY_RESOLVED',
  BILLING_RECORD_EXISTS = 'BILLING_RECORD_EXISTS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMITED = 'RATE_LIMITED',
}
